jenkinsci/remote-result-trigger-plugin

README.md

update scenes, move pic to this section

documentation: update scenes, move pic to this section

---

pom.xml

update cd config, plugin version with revision

---

pom.xml

add project url to pom.xml, will be used by plugin document.

add project url to pom.xml, will be used by plugin document.

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java
src/main/webapp/help.html

bug: fix trigger way, use trigger number replace checked number

bug: fix trigger way, use trigger number replace checked number

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultLogAction.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java
src/main/resources/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultLogAction/index.jelly

add trigger log action

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultLogAction.java

chore: add trigger log action

---

README.md
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteResultBuilder.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteResultJsonApi.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/CredentialsNotFoundException.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/JsonNotMatchException.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/UnSuccessfulRequestStatusException.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java
src/main/resources/io/jenkins/plugins/remote/result/trigger/RemoteResultBuilder/config.jelly

增加发布构建结果pipeline流程方法。
```[tasklist]
```

feat: publish result json

---

pom.xml
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultLogAction.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteResultBuilder.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/Auth2.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/CredentialsAuth.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/NoneAuth.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/TokenAuth.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/SourceMap.java

feat: clean code

---

src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/Auth2.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/SourceMap.java

feat: 为了触发构建发布操作

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java

bugfix: 版本保存在break之后导致无法缓存成功构建结果

---

src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java
src/main/resources/io/jenkins/plugins/remote/result/trigger/RemoteJobInfo/config.jelly
src/main/resources/io/jenkins/plugins/remote/result/trigger/RemoteJobInfo/help-remoteJobName.html

feat: 远程项目名称增加提示信息

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java

feat: 增加修改配置时清理旧构建结果信息功能

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteResultBuilder.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteResultJsonApi.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobJsonResultUtils.java

feat: 新增多分支流水线或者存在folder项目能正确发布json信息

---

src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java

fix: generateEnvs case null pointer exception

---

README.md
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java

feat: add REMOTE_JOBS env

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java

修复多个任务进行tigger时某个任务报错导致其他任务无法拉取远程信息的问题

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/RemoteJobInBuildingException.java

fix: 任务正在构建时，需要跳过该任务检查

---

src/test/java/io/jenkins/plugins/remote/result/trigger/auth2/Auth2Test.java

This PR aims to migrate all tests to JUnit5. Changes include:
* Migrate annotations and imports
* Migrate assertions
* Remove public visibility for test classes and methods
* Minor clean up
I am well aware that this is a quite large changeset however I hope that there is still interest in this PR and it will be reviewed.
If there are any questions, please do not hesitate to ping me.

Migrate tests to JUnit5

---

pom.xml
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTriggerProjectAction.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteJobInfo.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteResultBuilder.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/CredentialsAuth.java

Jenkins 2.479.3 provides Jakarta EE 9, Eclipse Jetty 12, Spring Security 6, and Java 17.
* Update plugin pom and baseline
* Remove deprecations
* Use Java 17 language features
* Minor cleanup
`mvn clean verify`

Require Jenkins 2.479.3 and Jakarta EE 9

---

pom.xml
src/main/java/io/jenkins/plugins/remote/result/trigger/ReadRemoteJobsStep.java
src/main/java/io/jenkins/plugins/remote/result/trigger/ReadRemoteResultStep.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTrigger.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteJenkinsServer.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteJobInfo.java
src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteResultBuilder.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/Auth2.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/CredentialsAuth.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/NoneAuth.java
src/main/java/io/jenkins/plugins/remote/result/trigger/auth2/TokenAuth.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/CredentialsNotFoundException.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/JsonNotMatchException.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/RemoteJobInBuildingException.java
src/main/java/io/jenkins/plugins/remote/result/trigger/exceptions/UnSuccessfulRequestStatusException.java
src/main/java/io/jenkins/plugins/remote/result/trigger/model/ResultCheck.java
src/main/resources/io/jenkins/plugins/remote/result/trigger/RemoteJobInfo/config.jelly

feat: 修改uid生成规则

---

src/main/java/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTriggerProjectAction.java
src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java
src/main/resources/io/jenkins/plugins/remote/result/trigger/RemoteBuildResultTriggerProjectAction/index.jelly

feat: 支持清理缓存

---

src/main/java/io/jenkins/plugins/remote/result/trigger/utils/RemoteJobResultUtils.java

fix: 当远程结果为list或者map等非String value时，通过环境变量获取时会发生类型强转报错；
